#!/bin/sh

URL_M='http://localhost:8080/ex03/cookie_crisp.php';
if [ $2 ]
then
    NAME=$2;
else
    NAME='coockie_name'
fi

if [ $3 ]
then
    VALUE=$3
else
    VALUE='coockie_value'
fi

if [ $1 == 'set' ]
then
    curl -c cook.txt "$URL_M?action=set&name=$NAME&value=$VALUE";
elif [ $1 == 'get' ]
then
curl -b cook.txt "$URL_M?action=get&name=$NAME&value=$VALUE";
elif [ $1 == 'del' ]
then
curl -c cook.txt "$URL_M?action=del&name=$NAME&value=$VALUE";
fi