#!/bin/sh

URL_M='http://localhost:8080/ex03/cookie_crisp.php';

if [ "$1" == 'set' ]
then
    curl -c cook.txt "$URL_M?action=set&name=plat&value=choucroute";
elif [ $1 == 'get' ]
then
curl -b cook.txt "$URL_M?action=get&name=plat&value=choucroute";
elif [ $1 == 'del' ]
then
curl -c cook.txt "$URL_M?action=del&name=plat&value=choucroute";
fi